config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "championships#index"

  get 'championships/index' => "championships#index", as: :championships
  get 'championships/:id' => "championships#show", as: :championship
  post 'championships/join/:id' => "championships#join", as: :join_championship

  get 'days/:id' => "days#show", as: :day

  post 'bets/create' => "bets#create", as: :create_bet
  put 'bets/update' => "bets#update", as: :update_bet

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  obfuscate_id

  has_many :teams
  has_many :days
  has_many :fixtures, through: :days
  has_many :user_scores

  validates :name, :start_date, :end_date, presence: :true
  validate :ends_after_starts

  def default_day
    days.first
  end

  private

  def ends_after_starts
    errors.add(:end_date, "Must ends after starts") unless end_date > start_date
  end
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :get_fixtures_to_bet, only: [:index]
  before_action :set_championship, except: [:index]


  def index
    @championships = Championship.all
  end

  def show
    unless @user.has_joined(@championship)
      flash[:alert] = "You must follow this chamionship to access it !"
      redirect_to championships_path
    end
    @players_user_scores = @championship.user_scores.order(value: :desc)
  end

  def join
    @user.user_scores.create!(championship: @championship)
    flash[:notice] = "Mrs. Borie wants to welcome you with the warmest hug you ever had !"
    redirect_to championship_path(@championship)
  end

  private

  def set_championship
    @championship = Championship.find(params[:id])
  end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/index.html.haml
.row
  .col-xs-12.text-center
    %h1 Welcome you Peignk !
.row
  - @championships.each do |c|
    .col-xs-12.text-center
      - if @user.has_joined(c)
        = link_to c.name, championship_path(c), class: "btn btn-default"
      - else
        = link_to c.name, "#", data: {championship_link: join_championship_path(c), championship_name: c.name, toggle: "modal", target: "#join-modal"}, class: "btn btn-default"

/ Modal
#join-modal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title
      .modal-body
        Do you want to join this championship ?
      .modal-footer
        %button.btn.btn-default{type: "button", data: {dismiss: "modal"}} No
        = link_to "Yes", "#", method: :post, class: 'btn btn-primary', id: "join-championship-link"

app/views/championships/show.html.haml
.row
  .col-xs-12
    = render "layouts/back_button", path: championships_path

.row
  .col-xs-12.text-center
    %h1= @championship.name

.row
  .col-xs-12.text-center
    = link_to "Fixtures", day_path(@championship.default_day), class: 'btn btn-primary btn-lg'

.row
  .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
    %h2.text-center Standings
    %table.table.table-striped
      %tr
        %th #
        %th Peignk
        %th Points
      - @players_user_scores.each_with_index do |us, idx|
        - user = us.user
        %tr{class: ("success" if user == @user)}
          %td= idx+1
          %td
            = image_tag user.facebook_picture_url, class: "img-circle user-picture", width: "30px"
            = user.name
          %td= us.value