config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "championships#index"

  get 'championships/index' => "championships#index", as: :championships
  get 'championships/:id' => "championships#show", as: :championship
  post 'championships/join/:id' => "championships#join", as: :join_championship

  get 'days/:id' => "days#show", as: :day

  post 'bets/create' => "bets#create", as: :create_bet
  put 'bets/update' => "bets#update", as: :update_bet

end

app/models/day.rb
class Day < ActiveRecord::Base
  obfuscate_id

  belongs_to :championship
  has_many :fixtures
  has_many :bets, through: :fixtures

  validates :championship, :date, :status, :name, presence: :true
  module Status
    REGULAR = 'regular'
    FINALS = 'finals'

    ALL = [REGULAR, FINALS]
  end
  STATUS = %w(regular finals)

  validates :status, inclusion: { in: Status::ALL  }
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_day
  before_action :set_championship
  before_action :set_user_score
  before_action :set_days
  before_action :set_fixtures

  def show
    unless @user.has_joined(@championship)
      flash[:alert] = "You must follow this chamionship to access it !"
      redirect_to championships_path
    end
  end

  private

  def set_day
    @day = Day.find(params[:id])
  end

  def set_championship
    @championship = @day.championship
  end

  def set_user_score
    @user_score = @user.user_scores.where(championship: @championship).first
  end

  def set_days
    @days = @championship.days.order(date: :asc)
  end

  def set_fixtures
    @fixtures = @day.fixtures
  end
end

app/helpers/days_helper.rb
module DaysHelper
  def bet_elements bet
    elements = []
    elements << (bet.result == "draw" ? "Draw" : "Winner: #{bet.winner.name}")

    unless bet.result == "draw"
      pg = bet.points_gap
      elements << "Points gap: #{pg.bottom}#{pg.top ? "-#{pg.top}" : "+"}"
    end

    if bet.bonus_off
      team_bonus_off = if (bet.bonus_off == "a")
        bet.fixture.team_a
      else
        bet.fixture.team_b
      end
      elements << "Bonus off: #{team_bonus_off.name}"
    end

    if bet.bonus_def
      team_bonus_def = if (bet.bonus_def == "a")
        bet.fixture.team_a
      else
        bet.fixture.team_b
      end
      elements << "Bonus def: #{team_bonus_def.name}"
    end

    elements.join(", ")
  end

  def display_result fixture, team_type
    score = ( team_type == "a" ? fixture.score_a : fixture.score_b)
    team = ( team_type == "a" ? fixture.team_a : fixture.team_b)
    "#{score} #{team.name}"
  end

  def display_bonus fixture, team_type
    bonus_def = true if ( fixture.bonus_def == team_type )
    bonus_off = true if ( fixture.bonus_off == team_type )

    if bonus_def || bonus_off
      bonus = []
      bonus << "Off" if bonus_off
      bonus << "Def" if bonus_def
      return "#{(bonus.join(", "))}"
    end
  end
end

app/views/days/_bet_form.html.haml
= form_for(bet, url: path, remote: true, html: { method: method, class: "form-horizontal bet-form" }) do |f|
  = f.hidden_field :fixture_id, value: fixture.id

  .form-group
    = f.label :result, class: "col-sm-2 control-label"
    .col-sm-6
      = f.select :result, options_for_select(bet_result_options_for_select(fixture)), {}, class: 'form-control result-select'

  .row.winner-fields-container{style: "display:none;"}
    .col-xs-12
      .form-group
        = f.label :points_gap_id, "Points gap", class: "col-sm-2 control-label"
        .col-sm-6
          = f.select :points_gap_id, options_for_select(bet_points_gap_options_for_select), {}, class: 'form-control'
      .form-group
        = f.label :bonus_off, "Defensive bonus", class: "col-sm-2 control-label"
        .col-sm-6
          = f.select :bonus_def, options_for_select(bet_bonus_options_for_select(fixture)), {}, class: 'form-control'

  .form-group
    = f.label :bonus_off, "Offensive bonus", class: "col-sm-2 control-label"
    .col-sm-6
      = f.select :bonus_off, options_for_select(bet_bonus_options_for_select(fixture)), {}, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-6
      = f.submit "Place bet", class: "btn btn-default"

app/views/days/_fixtures.html.haml
- today = Date.today
- @fixtures.each do |fixture|
  .col-xs-12.fixture-details
    .row
      .col-xs-12
        %p.small
          %strong
            = l(fixture.starts_at.to_date, format: :long)
    .row
      .col-xs-12
        %h3{class: ("winner" if fixture.winner == fixture.team_a)}
          = display_result(fixture, "a")
          %small= display_bonus(fixture, "a")
      .col-xs-12
        %h3{class: ("winner" if fixture.winner == fixture.team_b)}
          = display_result(fixture, "b")
          %small= display_bonus(fixture, "b")
    - if fixture.bets_closed?
      .row
        .col-xs-12.view-bets-trigger-container
          = link_to "View bets", "javascript:void(0)", class: "btn btn-default btn-xs"
        .col-xs-12.hide-bets-trigger-container{style: "display:none;"}
          = link_to "javascript:void(0)", class: "btn btn-danger" do
            %i.fa.fa-times
            Hide
        .col-xs-12.bets-container{style: "display:none;"}
          .row
          - fixture.bets.order(points: :desc).each do |b|
            - user = b.user
            .col-xs-12.bet{class: ("text-success" if user == @user)}
              = image_tag user.facebook_picture_url, class: "img-circle user-picture", width: "30px"
              %strong
                = b.points.to_i
                Pts
                \-
                = user.name
              \:
              = bet_elements(b)
    - elsif fixture.bettable?
      - bet = fixture.bet(@user_score)
      - if !!bet
        .row
          .col-xs-12.bet-details
            %h6 My bet :
            %p= bet_elements(bet)
          .col-xs-12.edit-bet-trigger-container
            = link_to "javascript:void(0)", class: "btn btn-default btn-xs" do
              %i.fa.fa-pencil
              Edit bet
          .col-xs-12.edit-bet-form-container{style: "display:none;"}
            = render "days/bet_form", bet: bet, path: update_bet_path, fixture: fixture, method: "put"
      - else
        .row
          .col-xs-12
            = render "days/bet_form", bet: Bet.new, path: create_bet_path, fixture: fixture, method: "post"
    .row
      .col-xs-12
        %hr

app/views/days/bets.js.erb
$('#fixtures').html("<%= j (render 'days/fixtures') %>");
$('#flash-messages').html("<%= j (render 'layouts/flash_messages') %>");

app/views/days/show.html.haml
.row
  .col-xs-12
    = render "layouts/back_button", path: championship_path(@championship)

.row
  .col-xs-12
    %h1
      = @championship.name

.row
  .col-xs-12.col-sm-4
    %form
      .form-group
        %select.form-control#day-selector
          - @days.each do |day|
            %option{value: day_path(day), selected: ("true" if @day == day)}= day.name

.row#fixtures
  = render "days/fixtures"