config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "championships#index"

  get 'championships/index' => "championships#index", as: :championships
  get 'championships/:id' => "championships#show", as: :championship
  post 'championships/join/:id' => "championships#join", as: :join_championship

  get 'days/:id' => "days#show", as: :day

  post 'bets/create' => "bets#create", as: :create_bet
  put 'bets/update' => "bets#update", as: :update_bet

end

app/views/layouts/_back_button.html.haml
= link_to path, class: "btn btn-default btn-xs" do
  %i.fa.fa-long-arrow-left
  back

app/views/layouts/_facebook_button.html.haml
= link_to omniauth_authorize_path(User, 'facebook') do
  %i.fa.fa-facebook-official
  Log in with Facebook

app/views/layouts/_flash_messages.html.erb
<div id="flash-messages">
  <% if flash[:notice] %>
    <div class="alert alert-info alert-dismissible text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Scoretognos", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle.user-menu{role: "button", aria: {expanded: "false", haspopup: "true"}, data: {toggle: "dropdown"}, href: "#"}
              = image_tag current_user.facebook_picture_url, class: "img-circle user-picture", width: "30px"
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to(destroy_user_session_path, method: "delete") do
                  Log Out
        - else
          %li
            = render "layouts/facebook_button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <html lang="en">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scoretognos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=843120129082701";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <div class="wrapper">
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </div>

</body>
</html>